//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace UmbracoDemoSite.Models.Umbraco
{
	/// <summary>GenericGridPage</summary>
	[PublishedContentModel("genericGridPage")]
	public partial class GenericGridPage : PublishedContentModel, IContentBase, ISeoMetas
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "genericGridPage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public GenericGridPage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<GenericGridPage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Content
		///</summary>
		[ImplementPropertyType("bodyText")]
		public Newtonsoft.Json.Linq.JToken BodyText
		{
			get { return UmbracoDemoSite.Models.Umbraco.ContentBase.GetBodyText(this); }
		}

		///<summary>
		/// Page Title: The title of the page, this is also the first text in a google search result. The ideal length is between 40 and 60 characters
		///</summary>
		[ImplementPropertyType("pageTitle")]
		public string PageTitle
		{
			get { return UmbracoDemoSite.Models.Umbraco.ContentBase.GetPageTitle(this); }
		}

		///<summary>
		/// Description
		///</summary>
		[ImplementPropertyType("description")]
		public string Description
		{
			get { return UmbracoDemoSite.Models.Umbraco.SeoMetas.GetDescription(this); }
		}

		///<summary>
		/// Tilte
		///</summary>
		[ImplementPropertyType("tilte")]
		public string Tilte
		{
			get { return UmbracoDemoSite.Models.Umbraco.SeoMetas.GetTilte(this); }
		}

		///<summary>
		/// Url Alias: Enter an alternative url
		///</summary>
		[ImplementPropertyType("umbracoUrlAlias")]
		public string UmbracoUrlAlias
		{
			get { return UmbracoDemoSite.Models.Umbraco.SeoMetas.GetUmbracoUrlAlias(this); }
		}
	}
}
