//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace UmbracoDemoSite.Models.Umbraco
{
	// Mixin content Type 2175 with alias "seoMetatags"
	/// <summary>Seo Metatags</summary>
	public partial interface ISeoMetatags : IPublishedContent
	{
		/// <summary>UmbracoUrlAlias</summary>
		string UmbracoUrlAlias { get; }
	}

	/// <summary>Seo Metatags</summary>
	[PublishedContentModel("seoMetatags")]
	public partial class SeoMetatags : PublishedContentModel, ISeoMetatags
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "seoMetatags";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public SeoMetatags(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<SeoMetatags, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// UmbracoUrlAlias
		///</summary>
		[ImplementPropertyType("umbracoUrlAlias")]
		public string UmbracoUrlAlias
		{
			get { return GetUmbracoUrlAlias(this); }
		}

		/// <summary>Static getter for UmbracoUrlAlias</summary>
		public static string GetUmbracoUrlAlias(ISeoMetatags that) { return that.GetPropertyValue<string>("umbracoUrlAlias"); }
	}
}
